### ISSUE TITLE
Crawler: Handle tsconfig.json while setup

### ISSUE THREAD

**Issue by BioPhoton** [timdeschryver/deprecation-manager#15]
If: Check for base `tsConfigPath` path in  `deprecation-crawler.config.json`. 
- [x] If the file exists take it.
- We have to keep in mind that the process should fail in `interactive` mode false. And we should name it `ci` mode as has to provide special behavior for CI only. 

Else: create separate tsconfig
- [x] Ask for base tsconfig
- [x] List related files
  - [x] Inform on how to change excludes includes.
  - [x] Create `tsconfig.deprecation-crawler.ts`

*Open Questions:*
 Should we commit that change?

**Comment by BioPhoton** [comment]
Added todo for CI mode in the code

**Comment by BioPhoton** [comment]
After revisiting this and our last discussion I restructured the process and kicked out the tsconfig generation at all.
If someone really needs a custom tsConfig we have the tsConfigPath property in the crawler config.

The idea behind it was to directly start the process with an additional commit step or so.

A better and easier in terms of implementation and maintenance is sticking to the tsConfigPath and providing a moving a pre-created config file into a folder ignored by the project. Or even create it on the fly into a specific folder by providing a command param with the direct path to `deprecation-crawler.config`.

New Process for a possible run-through:

Running `npx deprecation-crawler --configPath ./tmp/deprecation-crawler.config.json` should result in:

Looking for `./tmp/deprecation-crawler.config.json` 

- [ ] If: It exists it checks for the required defaults (tsConfigPath)
  - [ ] If: The tsConfigPath is set it will take it and go on with the setup phase.
  - [ ] Else: An error gets thrown
- [ ] Else: create asks all questions required and not set in as param to create the config
  - [ ] It will save the settings ./tmp/deprecation-crawler.config.json`

**Comment by timdeschryver** [comment]
I like the new run-through!
Should it throw if the config is not found, or should it ask the question to select the path?

**Comment by BioPhoton** [comment]
Updated the process with:
ask in user mode, throw in CI mode
