### ISSUE TITLE
Crawler: Repository-Sync-Phase behaviour

### ISSUE THREAD

**Issue by BioPhoton** [timdeschryver/deprecation-manager#34]
The repository sync phase AFAICT is only here to add the newly detected deprecations as link to the deprecation message.

`/*@deprecated This const is deprecated */` => `/*@deprecated This const is deprecated Details: http://www.myrepo.deprecations/#RUID*/`

The steps could look like the following:
Preconditions: Setup-Phase, Crawl-Phase

- √ Do you want to sync the repository with newly crawled ruid links?
  - If the repository has changes the process fails and the user is asked to commit the changes
    Same for CI mode
  - Else write changes to the code base

The (new) last step:
- √ Do you want to commit the updates to the codebase?
  - commit with message `docs(deprecation-manager): sync deprecations`  
  Note: this process should be done automatically in `CI` mode

**Comment by timdeschryver** [comment]
> If the repository has changes stash them

I don't think this will work. A new change could be a deprecation.
I think we should ask the user if she wants to add the links to the current changes, or if she wants to abort.

I like the `deprecation-management(repository-sync): sync deprecations` message. I think many projects use the semver commits, so I think we should do `chore: sync deprecations` or `docs: sync deprecations`

**Comment by BioPhoton** [comment]
We could stick to common approaches as say it is required to have a clean git state for this phase.
This is also what semantic release does and others. Also, we don't have to implement it :D

Updated comment with your feedback.

**Comment by timdeschryver** [comment]
If you're not working on this, I would like to take this one.
After giving this more thoughts I think the question "Do you want to persist the updates to the codebase" should be the very last question. It would also commit the output files (otherwise you would always end up with 2 commits for the deprecations).

**Comment by BioPhoton** [comment]
Perfect! Feel free to adopt my comment. I will use it for the Readme files.

**Comment by timdeschryver** [comment]
While I was testing this out, I ran into the issue that we create the config on the first run.
We could exclude the files that we create in the check to verify that the branch is clean.
But as pointed out before, we potentially make more changes... I would suggest to run this check before we start the crawl process. This means that if you want to run the deprecation-crawler, you have to be in a clean branch.

This would also make the implementation easier.

**Comment by BioPhoton** [comment]
Perfect! We can ask the user if we should commit it. Or not... I guess this is a general task reused across processes, right?
