### ISSUE TITLE
Validate deprecation messages 

### ISSUE THREAD

**Issue by BioPhoton** [timdeschryver/deprecation-manager#40]
We could implement a command to validate the message format of deprecation in code.

This could help to automate/enforce a format
See this discussion e. g. https://github.com/ReactiveX/rxjs/pull/5426#issuecomment-645106298

Idea:
We could create a group for that. We also have to prioritize these matches somehow.

**Comment by timdeschryver** [comment]
For me this is a low-priority and I'm not sure if we should implement it.
As you mentioned, it could be a group and the target repo can configure the groups for it.

**Comment by BioPhoton** [comment]
Yeah, groups are perfect!
